// oxlint-disable react/only-export-components -- the provider and hook intentionally share one typed context module.
import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Language = 'en' | 'zh-TW'

const en = {
  language: '中文', languageAria: 'Switch language to Traditional Chinese',
  navScan: 'Scan medicine', navWhy: 'Why it matters', navPharmacy: 'Find a pharmacy', account: 'Account', synced: 'Synced', myOcean: 'My Ocean',
  headerHome: 'MediCycle AI home', headerAccountSigned: 'Open MediCycle account, signed in', headerAccountGuest: 'Open MediCycle prototype account',
  heroEyebrow: 'AI × BEHAVIORAL SCIENCE × OCEAN CONSERVATION', heroTitle: 'Recognize the medicine.\nActivate better choices.', heroText: 'Turn one photo into disposal confidence, a safer next step, and an engaging journey toward ocean responsibility.', heroCta: 'SCAN A MEDICINE', demoFixed: 'On-device AI · Private photo',
  step1: 'Analyze photo', step1Text: 'Review an AI medicine-name candidate', step2: 'Plan a return', step2Text: 'Find and contact a nearby pharmacy', step3: 'Return completion', step3Text: 'Record the planned hand-off', step4: 'Unlock', step4Text: 'Reveal a marine life card', stepsAria: 'Four-step disposal journey',
  pharmacyAria: 'Nearby pharmacies', pharmacyEyebrow: 'ACTION SUPPORT · PLAN A RETURN OPTION', pharmacyTitle: 'Nearby pharmacies.', pharmacyIntro: 'These are nearby pharmacies, not verified medication return points. Contact the pharmacy to confirm medication take-back availability before visiting.', osmSearch: 'Uses OpenStreetMap search', useLocation: 'USE MY CURRENT LOCATION', finding: 'FINDING PHARMACIES…', viewSamples: 'VIEW SAMPLE PHARMACIES', privacyCoordinates: "Your coordinates are sent to this site's Cloudflare Function, which queries OpenStreetMap Overpass providers on the server. They are not stored by MediCycle.", allowLocation: 'Allow location access when your browser asks. This usually takes a few seconds.', liveResults: 'Live OpenStreetMap results within {radius} km · sorted nearest first · take-back availability is not verified', demoSample: 'DEMO SAMPLE DATA', demoSampleText: 'Showing sample pharmacies near Xitun District, Taichung.', locationError: 'We could not access your location. Enable Location Services for your browser, then try again.', locationTimeout: 'Your browser could not determine your location within 8 seconds. Check Location Services and try again.', searchTimeout: 'The pharmacy search timed out after trying multiple OpenStreetMap providers.', networkError: 'All OpenStreetMap pharmacy search providers are currently unavailable.', emptyResults: 'No pharmacies were found within 10 km.', retry: 'RETRY', viewSamplesInstead: 'VIEW SAMPLE RESULTS INSTEAD', sampleCenter: 'Sample search center', yourLocation: 'Your location', showOnMapAria: 'Show {name} on the map', phone: 'Phone', hours: 'Hours', osmTakeBack: 'OSM-listed drug recycling · contact pharmacy to confirm', unverifiedTakeBack: 'Unverified medication take-back — contact pharmacy to confirm', showOnMap: 'SHOW ON MAP', call: 'CALL', directions: 'DIRECTIONS', pharmacySource: 'Pharmacy locations and details come from OpenStreetMap contributors. OSM pharmacy data does not verify medication take-back participation.', returnPlanned: 'Return option planned', nextContactPlan: 'Next: make a contact plan', choosePharmacy: 'Choose a pharmacy you can contact to confirm medication take-back availability.', planRecorded: '✓ PLAN RECORDED', contactPharmacy: 'I WILL CONTACT A PHARMACY', nearbyNetwork: 'Nearby network', locations: '{count} locations', interactiveMap: 'Interactive map of nearby pharmacies', awayMeters: '{distance} m away', awayKm: '{distance} km away',
  session: 'SCAN SESSION', sessionEnded: 'Scan session ended', sessionPrivacy: 'For privacy and clarity, a result is not restored after refresh.', newScan: 'START NEW SCAN',
  fixedCase: 'Browser AI', fixedCaseText: 'YOLO11 medication-name candidates', privatePreview: 'Private processing', privatePreviewText: 'Selected photos stay on this device', guidedSteps: 'Guided steps', guidedStepsText: 'Recognition, planning, completion, reward', marineStories: 'Marine stories', marineStoriesText: 'Ocean impact collection',
  scanEyebrow: 'START HERE', scanTitle: 'Photograph a medicine. Get a cautious candidate.', scanText: 'Take or upload a clear photo. The YOLO11 model runs in this browser and returns a medicine-name candidate with confidence; it does not provide diagnosis or treatment advice.', demoNoAi: 'Private browser inference', demoNoAiText: 'The image is processed on this device with WebGPU when available and WASM as a fallback. Confirm any candidate from the original package or with a qualified professional.', takePhoto: 'TAKE A PHOTO', retakePhoto: 'RETAKE PHOTO', uploadDevice: 'UPLOAD FROM DEVICE', replacePhoto: 'REPLACE PHOTO', capturePhoto: 'CAPTURE PHOTO', cancelCamera: 'CANCEL CAMERA', cancel: 'CANCEL', continueDemo: 'ANALYZE PHOTO →', openingDemo: 'ANALYZING…', photoPreview: 'Photo preview', previewReady: 'Photo ready for analysis',
  browserInference: 'BROWSER AI · ON-DEVICE INFERENCE', selectedMedicinePreview: 'Selected medicine preview', analyzedMedicinePreview: 'Analyzed medicine photo with detection boxes', detectionOverlay: 'AI DETECTION OVERLAY · CANDIDATES ONLY', selectPhotoFirst: 'Take or upload a medicine photo first.', inferencePrivacy: 'The photo is analyzed locally in your browser and is not uploaded or stored by MediCycle.', modelLoading: 'Loading recognition model…', modelLoadingDetail: 'Preparing the on-device YOLO11 model. The first scan may take longer.', preparingImage: 'Preparing image…', preparingImageDetail: 'Letterboxing to 640 × 640 and creating an RGB tensor.', inferenceRunning: 'Analyzing medicine…', inferenceRunningDetail: 'Running the model in your browser.', inferenceComplete: 'Analysis complete', inferenceCompleteDetail: 'Review the candidate and confidence on the next screen.', unableReliable: 'Unable to identify reliably', retakeRequest: 'Try another photo with the package name sharp, well lit, and unobstructed.', modelLoadFailed: 'Model loading failed', modelLoadFailedDetail: 'The recognition model could not be loaded. Check the connection and try again.', inferenceFailed: 'Inference failed', inferenceFailedDetail: 'This photo could not be analyzed. Try a JPG or PNG image, or take another photo.',
  whyEyebrow: 'WHY IT MATTERS', whyTitle: 'Knowledge is not the finish line.\nBehavior change is.', whyText: 'MediCycle AI combines artificial intelligence with behavioral science. Recognition lowers the cognitive barrier, instant rewards sustain participation, and marine stories awaken awareness of environmental consequences.',
  oceanConnection: 'THE OCEAN CONNECTION', oceanTitle: 'Small residues. System-wide effects.', oceanText: 'Explore how pharmaceutical pollution can affect marine life across species, habitats, and generations.', reinforcement: 'POSITIVE REINFORCEMENT', collectionTitle: 'Turn responsible disposal into an ocean collection.', cardsUnlockedDevice: '{count} of 6 cards unlocked on this device', exploreCollection: 'EXPLORE THE COLLECTION',
  backPreview: '← BACK TO SCANNER', resultMode: 'ON-DEVICE AI · MEDICINE-NAME CANDIDATE', fixedDemonstration: 'AI CANDIDATE', noPhotoId: 'Confirm the candidate before acting.', resultEyebrow: 'AI MEDICINE-NAME CANDIDATE', resultCategory: 'Image recognition candidate · not a medical diagnosis', likelyMatch: 'LIKELY MATCH', possibleMatch: 'POSSIBLE MATCH', confidence: 'Model confidence', inferenceBackend: '{backend} · {ms} ms inference', candidateOnly: 'Candidate only', returnProfessional: 'RETURN TO A PROFESSIONAL COLLECTION POINT', resultNotice: 'Use the original packaging or ask a qualified professional to confirm the medicine name. No diagnosis or treatment is inferred.', medicalDisclaimer: 'This recognition result and disposal guidance are not medical advice. Do not start, stop, or change medication based on this result.', hormoneTherapy: 'Hormone therapy', endocrineRelated: 'Endocrine / thyroid-related', otherUnclassified: 'Other / unclassified', classificationLegend: 'Medicine classification highlight legend', detectedCandidates: 'Detected candidates', classificationMappingNote: 'Highlights follow a fixed reviewed mapping—not an AI pharmacology inference.', disposalEyebrow: 'YOUR DISPOSAL PLAN', disposalTitle: 'A safe hand-off, step by step.', disposalReason: 'If this medicine is unused or expired, keep it separate and contact a medical institution, pharmacy, or authorized collection program to confirm a suitable return option.', disposalStep1: 'Keep the medicine in its original packaging or medication bag.', disposalStep2: 'Do not flush it down a toilet or sink, and do not place it in household recycling.', disposalStep3: 'Use the pharmacy finder below and call before taking it to a medical institution or pharmacy.',
  completionEyebrow: 'STEP 03 · RETURN COMPLETION', completionDone: 'Completion recorded. Marine life unlocked.', completionReady: 'Return plan ready. Record the hand-off to unlock a card.', completionFind: 'Find and plan a return option before recording completion.', marineUnlocked: '✓ MARINE LIFE UNLOCKED', simulateUnlock: 'RECORD COMPLETION & UNLOCK', findPlan: 'FIND / PLAN A RETURN OPTION',
  quizEyebrow: 'STEP 04 · EMPATHY-BASED LEARNING', quizTitle: 'Turn awareness into knowledge.', quizIntro: 'Test what you learned about medication disposal, AI identification, and the ocean impact of pharmaceutical pollution.', quizComplete: 'QUIZ COMPLETE', quizPerfect: 'Ocean knowledge activated.', quizTryAgain: 'Every answer is a step toward safer water.', quizPerfectText: 'You connected responsible medication disposal with healthier marine ecosystems.', quizTryAgainText: 'Restart the quiz to review the questions and strengthen what you learned.', restartQuiz: 'RESTART QUIZ', question: 'QUESTION', questionAria: 'Question {current} of {total}', correct: 'Correct.', incorrect: 'Incorrect.', detailedExplanation: 'DETAILED EXPLANATION', whyCorrect: 'Why the correct answer is right', otherOptions: 'Why the other choices do not fit', trustedSources: 'Trusted sources', viewResults: 'VIEW RESULTS', nextQuestion: 'NEXT QUESTION',
  backHome: '← BACK HOME', oceanStory: 'BEHAVIOR → IMPACT → STORY', oceanBuild: 'Build an ocean worth protecting.', activityCompleteText: 'Six responsible disposal actions have revealed the complete marine collection. Every card makes an invisible environmental choice visible—and turns repeated action into a lasting habit.', activityText: 'Each responsible disposal action reveals a marine life card. Return to the scanner to keep building your collection and connect everyday choices with ocean health.', cardsProgress: '{count} of 6 cards unlocked', collectionComplete: 'Collection complete', secretSpecies: 'Secret species', unlocked: 'UNLOCKED', lockedHint: 'COMPLETE A SAFE DISPOSAL TO REVEAL', resetProgress: 'RESET DEMO PROGRESS', collectionCompleteEyebrow: 'OCEAN COLLECTION COMPLETE', collectionContinueEyebrow: 'KEEP THE OCEAN GROWING', collectionCompleteTitle: 'Six safer choices. One ocean worth protecting.', collectionContinueTitle: 'Your next safe return reveals another species.', continueImpact: 'CONTINUE THE IMPACT',
  prototypeAccount: 'PROTOTYPE ACCOUNT', accountTitle: 'Keep your ocean progress.', accountIntro: 'This is a prototype phone-and-PIN account. It does not send an SMS and does not verify ownership of the phone number.', signedInStatus: 'Signed in · progress sync is on', savedProgress: 'Saved progress', marineCards: 'Marine cards', bestQuiz: 'Best quiz', demoCompletions: 'Demo completions', logOut: 'LOG OUT', resetMyProgress: 'RESET MY PROGRESS', firstTime: 'FIRST TIME', signIn: 'SIGN IN', phoneNumber: 'Phone number', countryCode: 'Include country code', createPin: 'Create a 6-digit PIN', pin: '6-digit PIN', pleaseWait: 'PLEASE WAIT…', createAccount: 'CREATE PROTOTYPE ACCOUNT', signInRestore: 'SIGN IN & RESTORE', accountPrivacy: 'Your phone number is used only to identify and restore your MediCycle progress. It is not used for marketing.', closeAccount: 'Close account', pinError: 'PIN must contain exactly 6 digits.', accountUnavailable: 'The account service is unavailable.', couldNotLogout: 'Could not log out.', couldNotReset: 'Could not reset progress.', resetConfirm: 'Reset your synced MediCycle progress? Your account will remain available.',
  footer: 'Smart hormone medication recycling through AI, behavioral science, and ocean empathy.', secretCard: 'SECRET MARINE LIFE CARD', youUnlocked: 'You unlocked {name}!', continueQuiz: 'CONTINUE TO IMPACT CHECK', closeCard: 'Close card',
} as const

const zh: Record<keyof typeof en, string> = {
  language: 'EN', languageAria: '切換語言為英文', navScan: '掃描藥品', navWhy: '為何重要', navPharmacy: '尋找藥局', account: '帳戶', synced: '已同步', myOcean: '我的海洋', headerHome: 'MediCycle AI 首頁', headerAccountSigned: '開啟 MediCycle 帳戶（已登入）', headerAccountGuest: '開啟 MediCycle 體驗帳戶',
  heroEyebrow: 'AI × 行為科學 × 海洋保育', heroTitle: '辨識藥品。\n啟動更好的選擇。', heroText: '把一張照片化為清楚的回收判斷、安全的下一步，以及守護海洋的互動旅程。', heroCta: '掃描藥品', demoFixed: '裝置端 AI · 照片保持私密',
  step1: '分析照片', step1Text: '查看 AI 藥名候選', step2: '規劃回收', step2Text: '尋找並聯絡附近藥局', step3: '完成回收', step3Text: '記錄規劃的交付流程', step4: '解鎖', step4Text: '揭曉海洋生物卡', stepsAria: '四步驟藥品回收流程',
  pharmacyAria: '附近藥局', pharmacyEyebrow: '行動支援 · 規劃回收選項', pharmacyTitle: '附近藥局', pharmacyIntro: '以下為附近藥局，不代表已確認提供藥品回收。前往前請先聯絡藥局確認是否接受回收。', osmSearch: '使用 OpenStreetMap 搜尋', useLocation: '使用我的目前位置', finding: '正在尋找藥局…', viewSamples: '查看範例藥局', privacyCoordinates: '您的座標會傳送至本站的 Cloudflare Function，由伺服器查詢 OpenStreetMap Overpass 服務；MediCycle 不會儲存座標。', allowLocation: '瀏覽器詢問時請允許位置存取，通常只需幾秒鐘。', liveResults: '顯示 {radius} 公里內的即時 OpenStreetMap 結果 · 依距離排序 · 尚未驗證藥品回收服務', demoSample: '體驗範例資料', demoSampleText: '顯示台中市西屯區附近的範例藥局。', locationError: '無法取得您的位置。請開啟瀏覽器定位服務後再試一次。', locationTimeout: '瀏覽器未能在 8 秒內確認位置，請檢查定位服務後重試。', searchTimeout: '藥局搜尋逾時，已嘗試多個 OpenStreetMap 服務。', networkError: 'OpenStreetMap 藥局搜尋服務目前皆無法使用。', emptyResults: '10 公里內找不到藥局。', retry: '重試', viewSamplesInstead: '改看範例結果', sampleCenter: '範例搜尋中心', yourLocation: '您的位置', showOnMapAria: '在地圖上顯示 {name}', phone: '電話', hours: '營業時間', osmTakeBack: 'OSM 標示藥品回收 · 請聯絡藥局確認', unverifiedTakeBack: '未驗證藥品回收服務 — 請聯絡藥局確認', showOnMap: '顯示於地圖', call: '致電', directions: '路線', pharmacySource: '藥局位置與詳細資料來自 OpenStreetMap 貢獻者；OSM 藥局資料不代表已確認提供藥品回收。', returnPlanned: '已規劃回收選項', nextContactPlan: '下一步：建立聯絡計畫', choosePharmacy: '選擇一家可聯絡並確認藥品回收服務的藥局。', planRecorded: '✓ 已記錄計畫', contactPharmacy: '我會聯絡藥局', nearbyNetwork: '附近藥局網絡', locations: '{count} 個地點', interactiveMap: '附近藥局互動地圖', awayMeters: '距離 {distance} 公尺', awayKm: '距離 {distance} 公里',
  session: '掃描階段', sessionEnded: '掃描已結束', sessionPrivacy: '為保護隱私並避免混淆，重新整理後不會還原結果。', newScan: '開始新的掃描', fixedCase: '瀏覽器 AI', fixedCaseText: 'YOLO11 藥名候選', privatePreview: '私密處理', privatePreviewText: '所選照片只留在此裝置', guidedSteps: '四步驟引導', guidedStepsText: '辨識、規劃、完成、獎勵', marineStories: '海洋故事', marineStoriesText: '海洋影響收藏',
  scanEyebrow: '從這裡開始', scanTitle: '拍攝藥品，取得謹慎的候選結果。', scanText: '拍攝或上傳清晰照片。YOLO11 模型會在瀏覽器內運行，以信心分數顯示藥名候選；不提供診斷或處置建議。', demoNoAi: '私密的瀏覽器推論', demoNoAiText: '影像會在此裝置上處理，可用時優先使用 WebGPU，否則改用 WASM。請以原包裝或向合格專業人員確認候選結果。', takePhoto: '拍攝照片', retakePhoto: '重新拍攝', uploadDevice: '從裝置上傳', replacePhoto: '更換照片', capturePhoto: '拍照', cancelCamera: '取消相機', cancel: '取消', continueDemo: '分析照片 →', openingDemo: '正在分析…', photoPreview: '照片預覽', previewReady: '照片已可開始分析',
  browserInference: '瀏覽器 AI · 裝置端推論', selectedMedicinePreview: '所選的藥品照片預覽', analyzedMedicinePreview: '含辨識框的已分析藥品照片', detectionOverlay: 'AI 辨識框 · 僅為候選結果', selectPhotoFirst: '請先拍攝或上傳藥品照片。', inferencePrivacy: '照片僅在您的瀏覽器內分析，MediCycle 不會上傳或儲存。', modelLoading: '正在載入辨識模型…', modelLoadingDetail: '正在準備裝置端 YOLO11 模型，首次掃描可能較久。', preparingImage: '正在準備影像…', preparingImageDetail: '正在以 letterbox 轉為 640 × 640 RGB tensor。', inferenceRunning: '正在分析藥品…', inferenceRunningDetail: '模型正在您的瀏覽器內運行。', inferenceComplete: '分析完成', inferenceCompleteDetail: '請在下一頁查看候選結果與信心分數。', unableReliable: '無法可靠辨識', retakeRequest: '請重新拍攝，並讓包裝藥名清晰、光線充足且無遮擋。', modelLoadFailed: '模型載入失敗', modelLoadFailedDetail: '無法載入辨識模型，請檢查網路後重試。', inferenceFailed: '推論失敗', inferenceFailedDetail: '無法分析此照片。請改用 JPG 或 PNG，或重新拍攝。',
  whyEyebrow: '為何重要', whyTitle: '知識不是終點。\n改變行為才是。', whyText: 'MediCycle AI 結合人工智慧與行為科學：辨識降低思考門檻、即時獎勵維持參與，海洋故事則喚起對環境後果的認知。', oceanConnection: '與海洋的連結', oceanTitle: '微量殘留，系統性影響。', oceanText: '探索藥物污染如何跨越物種、棲地與世代影響海洋生命。', reinforcement: '正向強化', collectionTitle: '把負責任的回收化為海洋收藏。', cardsUnlockedDevice: '此裝置已解鎖 {count} / 6 張卡片', exploreCollection: '探索收藏',
  backPreview: '← 返回掃描', resultMode: '裝置端 AI · 藥名候選', fixedDemonstration: 'AI 候選', noPhotoId: '行動前請先確認候選結果。', resultEyebrow: 'AI 藥名候選', resultCategory: '影像辨識候選｜非醫療診斷', likelyMatch: '很可能是', possibleMatch: '可能是', confidence: '模型信心分數', inferenceBackend: '{backend} · 推論 {ms} 毫秒', candidateOnly: '僅為候選結果', returnProfessional: '送至專業回收據點', resultNotice: '請以原包裝或詢問合格專業人員確認藥名。系統不會推斷診斷或處置。', medicalDisclaimer: '此辨識結果與回收指引不構成醫療建議。請勿根據此結果開始、停止或變更用藥。', hormoneTherapy: '荷爾蒙治療', endocrineRelated: '內分泌／甲狀腺相關', otherUnclassified: '其他／未分類', classificationLegend: '藥物分類特殊標示圖例', detectedCandidates: '辨識候選清單', classificationMappingNote: '特殊標示依固定人工審閱 mapping，不由 AI 推斷藥理分類。', disposalEyebrow: '您的回收計畫', disposalTitle: '安全交付，按步完成。', disposalReason: '若此藥品未使用或已過期，請分開保留，並聯絡醫療機構、藥局或合法回收計畫，確認合適的回收方式。', disposalStep1: '將藥品保留在原包裝或藥袋中。', disposalStep2: '不要沖入馬桶或水槽，也不要放進家用資源回收。', disposalStep3: '使用下方藥局搜尋，前往醫療機構或藥局前先致電確認。',
  completionEyebrow: '步驟 03 · 完成回收', completionDone: '已記錄完成，並解鎖海洋生物。', completionReady: '回收計畫已準備好，記錄交付即可解鎖卡片。', completionFind: '請先尋找並規劃回收選項，再記錄完成。', marineUnlocked: '✓ 已解鎖海洋生物', simulateUnlock: '記錄完成並解鎖', findPlan: '尋找／規劃回收選項',
  quizEyebrow: '步驟 04 · 同理學習', quizTitle: '把認知轉化為知識。', quizIntro: '測試您對藥品回收、AI 辨識與藥物污染海洋影響的理解。', quizComplete: '測驗完成', quizPerfect: '海洋知識已啟動。', quizTryAgain: '每個答案都是邁向潔淨水域的一步。', quizPerfectText: '您已將正確藥品回收與更健康的海洋生態連結起來。', quizTryAgainText: '重新開始測驗，複習題目並加深理解。', restartQuiz: '重新測驗', question: '問題', questionAria: '第 {current} 題，共 {total} 題', correct: '答對了。', incorrect: '答錯了。', detailedExplanation: '詳細解析', whyCorrect: '為什麼正確答案正確', otherOptions: '為什麼其他選項不合適', trustedSources: '可信來源', viewResults: '查看結果', nextQuestion: '下一題',
  backHome: '← 返回首頁', oceanStory: '行為 → 影響 → 故事', oceanBuild: '打造值得守護的海洋。', activityCompleteText: '六次負責任的回收行動已揭曉完整海洋收藏。每張卡片讓看不見的環境選擇變得可見，並將重複行動化為長久習慣。', activityText: '每次負責任的回收行動都會揭曉一張海洋生物卡。回到掃描流程繼續收藏，將日常選擇與海洋健康連結起來。', cardsProgress: '已解鎖 {count} / 6 張卡片', collectionComplete: '收藏完成', secretSpecies: '神秘物種', unlocked: '已解鎖', lockedHint: '完成安全回收即可揭曉', resetProgress: '重設體驗進度', collectionCompleteEyebrow: '海洋收藏完成', collectionContinueEyebrow: '讓海洋持續成長', collectionCompleteTitle: '六個更安全的選擇，守護同一片海洋。', collectionContinueTitle: '下一次安全回收，將揭曉另一個物種。', continueImpact: '繼續創造影響', prototypeAccount: '體驗帳戶', accountTitle: '保存您的海洋進度。', accountIntro: '這是使用電話與 PIN 的體驗帳戶，不會傳送簡訊，也不會驗證電話號碼所有權。', signedInStatus: '已登入 · 進度同步已開啟', savedProgress: '已儲存進度', marineCards: '海洋卡片', bestQuiz: '最佳測驗', demoCompletions: '體驗完成次數', logOut: '登出', resetMyProgress: '重設我的進度', firstTime: '首次使用', signIn: '登入', phoneNumber: '電話號碼', countryCode: '請包含國碼', createPin: '建立 6 位數 PIN', pin: '6 位數 PIN', pleaseWait: '請稍候…', createAccount: '建立體驗帳戶', signInRestore: '登入並還原', accountPrivacy: '您的電話號碼僅用於識別與還原 MediCycle 進度，不會用於行銷。', closeAccount: '關閉帳戶', pinError: 'PIN 必須剛好為 6 位數字。', accountUnavailable: '帳戶服務目前無法使用。', couldNotLogout: '無法登出。', couldNotReset: '無法重設進度。', resetConfirm: '要重設已同步的 MediCycle 進度嗎？您的帳戶仍會保留。', footer: '以 AI、行為科學與海洋同理心推動智慧荷爾蒙藥物回收。', secretCard: '神秘海洋生物卡', youUnlocked: '您解鎖了{name}！', continueQuiz: '繼續影響力測驗', closeCard: '關閉卡片',
}

type Key = keyof typeof en
type I18nContextValue = { language: Language; setLanguage: (language: Language) => void; toggleLanguage: () => void; t: (key: Key, variables?: Record<string, string | number>) => string }
const I18nContext = createContext<I18nContextValue | null>(null)
const STORAGE_KEY = 'medicycle-language'

function initialLanguage(): Language {
  const saved = window.localStorage.getItem(STORAGE_KEY)
  if (saved === 'en' || saved === 'zh-TW') return saved
  return /^(zh-TW|zh-Hant|zh)(-|$)/i.test(navigator.language) ? 'zh-TW' : 'en'
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(initialLanguage)
  useEffect(() => { window.localStorage.setItem(STORAGE_KEY, language); document.documentElement.lang = language }, [language])
  const value = useMemo<I18nContextValue>(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage((current) => current === 'en' ? 'zh-TW' : 'en'),
    t: (key, variables = {}) => Object.entries(variables).reduce((text, [name, replacement]) => text.replaceAll(`{${name}}`, String(replacement)), (language === 'zh-TW' ? zh : en)[key]),
  }), [language])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const value = useContext(I18nContext)
  if (!value) throw new Error('useI18n must be used inside I18nProvider')
  return value
}
